2014-07-04 19:01:48 INFO juju-log shared-db:45: Wrote template /etc/haproxy/haproxy.cfg.
2014-07-04 19:01:48 INFO juju-log shared-db:45: Migrating the nova database.
2014-07-04 19:01:49 INFO shared-db-relation-changed 2014-07-04 19:01:49.908 11320 INFO migrate.versioning.api [-] 215 -> 216...
2014-07-04 19:02:07 INFO shared-db-relation-changed 2014-07-04 19:02:07.057 11320 CRITICAL nova [-] IntegrityError: (IntegrityError) (1062, "Duplicate entry 'juju-machin
e-0-lxc-0-conductor-0' for key 'uniq_services0host0topic0deleted'") 'ALTER TABLE services ADD CONSTRAINT uniq_services0host0topic0deleted UNIQUE (host, topic, deleted)'
()
2014-07-04 19:02:07 INFO shared-db-relation-changed 2014-07-04 19:02:07.057 11320 TRACE nova Traceback (most recent call last):
2014-07-04 19:02:07 INFO shared-db-relation-changed 2014-07-04 19:02:07.057 11320 TRACE nova File "/usr/bin/nova-manage", line 10, in <module>
2014-07-04 19:02:07 INFO shared-db-relation-changed 2014-07-04 19:02:07.057 11320 TRACE nova sys.exit(main())
2014-07-04 19:02:07 INFO shared-db-relation-changed 2014-07-04 19:02:07.057 11320 TRACE nova File "/usr/lib/python2.7/dist-packages/nova/cmd/manage.py", line 1374, in
main
2014-07-04 19:02:07 INFO shared-db-relation-changed 2014-07-04 19:02:07.057 11320 TRACE nova ret = fn(*fn_args, **fn_kwargs)
2014-07-04 19:02:07 INFO shared-db-relation-changed 2014-07-04 19:02:07.057 11320 TRACE nova File "/usr/lib/python2.7/dist-packages/nova/cmd/manage.py", line 883, in s
ync
2014-07-04 19:02:07 INFO shared-db-relation-changed 2014-07-04 19:02:07.057 11320 TRACE nova return migration.db_sync(version)
2014-07-04 19:02:07 INFO shared-db-relation-changed 2014-07-04 19:02:07.057 11320 TRACE nova File "/usr/lib/python2.7/dist-packages/nova/db/migration.py", line 29, in
db_sync
2014-07-04 19:02:07 INFO shared-db-relation-changed 2014-07-04 19:02:07.057 11320 TRACE nova return IMPL.db_sync(version=version)
2014-07-04 19:02:07 INFO shared-db-relation-changed 2014-07-04 19:02:07.057 11320 TRACE nova File "/usr/lib/python2.7/dist-packages/nova/db/sqlalchemy/migration.py", l
ine 44, in db_sync
2014-07-04 19:02:07 INFO shared-db-relation-changed 2014-07-04 19:02:07.057 11320 TRACE nova return versioning_api.upgrade(get_engine(), repository, version)
2014-07-04 19:02:07 INFO shared-db-relation-changed 2014-07-04 19:02:07.057 11320 TRACE nova File "/usr/lib/python2.7/dist-packages/migrate/versioning/api.py", line 18
6, in upgrade
2014-07-04 19:02:07 INFO shared-db-relation-changed 2014-07-04 19:02:07.057 11320 TRACE nova return _migrate(url, repository, version, upgrade=True, err=err, **opts)
2014-07-04 19:02:07 INFO shared-db-relation-changed 2014-07-04 19:02:07.057 11320 TRACE nova File "<string>", line 2, in _migrate
2014-07-04 19:02:07 INFO shared-db-relation-changed 2014-07-04 19:02:07.057 11320 TRACE nova File "/usr/lib/python2.7/dist-packages/migrate/versioning/util/__init__.py", line 159, in with_engine
2014-07-04 19:02:07 INFO shared-db-relation-changed 2014-07-04 19:02:07.057 11320 TRACE nova return f(*a, **kw)
2014-0...
2017-09-13 10:34:00.502941 7fdd72b22700 1 ====== starting new request req=0x7fdd72b1c1f0 =====
2017-09-13 10:34:00.505116 7fdd72b22700 1 ====== req done req=0x7fdd72b1c1f0 op status=0 http_status=200 ======
2017-09-13 10:34:00.505172 7fdd72b22700 1 civetweb: 0x6d8c1c6000: 10.5.8.74 - - [13/Sep/2017:06:28:33 +0700] "GET /admin/log?type=metadata&id=63&period=487a3057-60be-4d61-8720-eb2897900b71&max-entries=100&&rgwx-zonegroup=db34009a-7776-46ae-b94f-e81455254df3 HTTP/1.1" 1 0 - - > /var/log/ceph/ceph-mgr.hoannv-ceph-luminous-1.log <
2017-09-13 10:34:01.048738 7f8c84ff8700 1 mgr send_beacon active > /var/log/ceph/ceph-mon.hoannv-ceph-luminous-1.log <
2017-09-13 10:34:01.536263 7fd9b1adf700 0 mon.hoannv-ceph-luminous-1@1(peon).data_health(34) update_stats avail 91% total 64498 MB, used 2744 MB, avail 59098 MB > /var/log/ceph/ceph-client.rgw.hoannv-ceph-luminous-1.log <
2017-09-13 10:34:02.603720 7fdd9fd83700 0 data sync: ERROR: failed to fetch datalog info
2017-09-13 10:34:02.754777 7fdd72b22700 1 ====== starting new request req=0x7fdd72b1c1f0 =====
2017-09-13 10:34:02.756553 7fdd72b22700 1 ====== req done req=0x7fdd72b1c1f0 op status=0 http_status=200 ======
2017-09-13 10:34:02.756607 7fdd72b22700 1 civetweb: 0x6d8c1c6000: 10.5.8.74 - - [13/Sep/2017:06:28:33 +0700] "GET /admin/log?type=metadata&id=3&period=487a3057-60be-4d61-8720-eb2897900b71&max-entries=100&&
rgwx-zonegroup=db34009a-7776-46ae-b94f-e81455254df3 HTTP/1.1" 1 0 - - > /var/log/ceph/ceph-mgr.hoannv-ceph-luminous-1.log <
2017-09-13 10:34:03.049440 7f8c84ff8700 1 mgr send_beacon active > /var/log/ceph/ceph-client.rgw.hoannv-ceph-luminous-1.log <
2017-09-13 10:34:03.662665 7fdd72b22700 1 ====== starting new request req=0x7fdd72b1c1f0 =====
2017-09-13 10:34:03.664785 7fdd72b22700 1 ====== req done req=0x7fdd72b1c1f0 op status=0 http_status=200 ======
2017-09-13 10:34:03.664832 7fdd72b22700 1 civetweb: 0x6d8c1c6000: 10.5.8.74 - - [13/Sep/2017:06:28:33 +0700] "GET /admin/log?type=metadata&id=9&period=487a3057-60be-4d61-8720-eb2897900b71&max-entries=100&&
rgwx-zonegroup=db34009a-7776-46ae-b94f-e81455254df3 HTTP/1.1" 1 0 - -
2017-09-13 10:34:03.922128 7fdd72b22700 1 ====== starting new request req=0x7fdd72b1c1f0 =====
2017-09-13 10:34:03.924847 7fdd72b22700 1 ====== req done req=0x7fdd72b1c1f0 op status=0 http_status=200 ======
2017-09-13 10:34:03.924894 7fdd72b22700 1 civetweb: 0x6d8c1c6000: 10.5.8.74 - - [13/Sep/2017:06:28:33 +0700] "GET /admin/log?type=metadata&id=2&period=487a3057-60be-4d61-8720-eb2897900b71&max-entries=100&&
rgwx-zonegroup=db34009a-7776-46ae-b94f-e81455254df3 HTTP/1.1" 1 0 - -
2017-09-13 10:34:04.125128 7fdd72b22700 1 ====== starting new request req=0x7fdd72b1c1f0 =====
2017-09-13 10:34:04.127026 7fdd72b22700 1 ====== req done req=0x7fdd72b1c1f0 op status=0 http_status=200 ======
2017-09-13 10:34:04.127069 7fdd72b22700 1 civetweb: 0x6d8c1c6000: 10.5.8.74 - - [13/Sep/2017:06:28:33 +0700] "GET /admin/log?type=metadata&id=39&period=487a3057-60be-4d61-8720-eb2897900b71&max-entries=100&
&rgwx-zonegroup=db34009a-7776-46ae-b94f-e81455254df3 HTTP/1.1" 1 0 - - 
2017-09-13 10:32:17.971232 7f360a19a700 1 meta sync: ERROR: failed to read mdlog info with (2) No such file or directory
2017-09-13 10:32:19.660778 7f360a19a700 1 meta sync: ERROR: failed to read mdlog info with (2) No such file or directory
2017-09-13 10:32:22.603664 7f3514da9700 1 ====== starting new request req=0x7f3514da31f0 =====
2017-09-13 10:32:22.603935 7f3514da9700 1 ====== req done req=0x7f3514da31f0 op status=0 http_status=403 ======
2017-09-13 10:32:22.603988 7f3514da9700 1 civetweb: 0xa58d251000: 10.5.8.88 - - [13/Sep/2017:10:32:22 +0700] "GET /admin/log?type=data&rgwx-zonegroup=db34009a-7776-46ae-b94f-e81455254df3 HTTP/1.1" 1 0 - -
2017-09-13 10:32:22.629490 7f360a19a700 1 meta sync: ERROR: failed to read mdlog info with (2) No such file or directory
2017-09-13 10:32:23.089541 7f360a19a700 1 meta sync: ERROR: failed to read mdlog info with (2) No such file or directory
    raise value
  File "/opt/conda/3/anteia/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/conda/3/anteia/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/conda/3/anteia/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/conda/3/anteia/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/conda/3/anteia/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/conda/3/anteia/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/conda/3/anteia/app/init.py", line 78, in stream
    res = Analyth.ApiCheck(arg)
  File "/opt/conda/3/anteia/app/modulos/Analyth.py", line 61, in ApiCheck
    output = Calls.Command(command)
  File "/opt/conda/3/anteia/app/modulos/Calls.py", line 7, in Command
    out = check_output([command], shell=True)
  File "/usr/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['scripts/palillos.sh start all all all']' returned non-zero exit status 126.
127.0.0.1 - - [15/Jan/2020 12:40:50] "GET /api?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [15/Jan/2020 12:40:50] "GET /api?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [15/Jan/2020 12:40:50] "GET /api?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [15/Jan/2020 12:40:50] "GET /api?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [15/Jan/2020 12:40:58] "GET /api?enviroment=dev&namespace=all&pod=all&container=all&action=start&tech=kubernetes HTTP/1.1" 200 -
127.0.0.1 - - [15/Jan/2020 12:41:12] "GET /api HTTP/1.1" 200 -
127.0.0.1 - - [15/Jan/2020 12:41:17] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [15/Jan/2020 12:41:19] "GET /dashboard HTTP/1.1" 200 -
127.0.0.1 - - [15/Jan/2020 15:13:53] "GET /api HTTP/1.1" 200 -
127.0.0.1 - - [15/Jan/2020 15:13:57] "GET /dashboard HTTP/1.1" 200 -
127.0.0.1 - - [15/Jan/2020 15:14:02] "GET /dashboard/ HTTP/1.1" 404 -
127.0.0.1 - - [15/Jan/2020 15:14:06] "GET /dashboard/kubernetes HTTP/1.1" 200 -
127.0.0.1 - - [15/Jan/2020 17:32:20] "POST /dashboard/kubernetes HTTP/1.1" 302 -
127.0.0.1 - - [15/Jan/2020 17:32:20] "GET /api?enviroment=dev&namespace=none&pod=cards-daily-reports-batch-processor-1577815200-7qr78&container=cards-daily-reports-batch-processor-1577815200-f429w&action=stop&tech=kubernetes HTTP/1.1" 200 -
127.0.0.1 - - [16/Jan/2020 09:15:13] "GET /favicon.ico HTTP/1.1" 404 -
